Repository trustbloc/edge-core, pull requests merged in 2020-11, with the labels that each got.

#96 feat: #95 zcapld - validate proofs
  go.mod
  go.sum
  pkg/zcapld/resolve.go
  pkg/zcapld/resolve_test.go
  pkg/zcapld/testdata/context/w3id.org.security.v1.json
  pkg/zcapld/testdata/context/w3id.org.security.v2.json
  pkg/zcapld/verify.go
  pkg/zcapld/verify_test.go
  pkg/zcapld/zcap.go
Labels: cla-signed, enhancement, zcaps

#99 feat: #97 zcapld: create API
  pkg/zcapld/create.go
  pkg/zcapld/create_test.go
  pkg/zcapld/zcap.go
Labels: cla-signed, enhancement, zcaps

#100 feat: #98 zcapld: support did:key
  pkg/zcapld/didkey_test.go
  pkg/zcapld/resolve.go
  pkg/zcapld/resolve_test.go
Labels: cla-signed, enhancement, zcaps

#107 feat: #101 zcaps - middleware
  go.mod
  go.sum
  pkg/zcapld/middleware.go
  pkg/zcapld/middleware_test.go
Labels: cla-signed, enhancement, zcaps

#110 fix: not exporting private keys to httpsignature library
  pkg/zcapld/middleware.go
  pkg/zcapld/middleware_test.go
  pkg/zcapld/util_test.go
  pkg/zcapld/verify_test.go
Labels: bug, cla-signed

#111 feat: add cmd method to get optional arg
  pkg/utils/cmd/util.go
  pkg/utils/cmd/util_test.go
Labels: cla-signed

#112 chore: update aries-framework-go revision
  go.mod
  go.sum
  pkg/zcapld/resolve.go
Labels: cla-signed

#114 feat: #113 zcaps: support delegation chains of arbitrary length
  pkg/zcapld/middleware_test.go
  pkg/zcapld/verify.go
  pkg/zcapld/verify_test.go
Labels: cla-signed, enhancement, zcaps

#115 chore: update aries revision
  go.mod
  go.sum
Labels: cla-signed

#117 feat: CouchDB query bookmark support
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/errors.go
  pkg/storage/mysql/mysqlstore.go
  pkg/storage/mysql/mysqlstore_test.go
  pkg/storage/store.go
Labels: cla-signed

#118 fix: zcapld middleware returning 200 when validation fails
  pkg/zcapld/middleware.go
  pkg/zcapld/middleware_test.go
Labels: bug, cla-signed, zcaps
