Repository trustbloc/edge-core, pull requests merged in 2020-10, with the labels that each got.

#80 fix: Added log check to CouchDB index unit test
  pkg/storage/couchdb/couchdbstore_test.go
Labels: cla-signed

#82 fix: allows deleted documents to be stored again
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/couchdb/errors.go
Labels: bug, cla-signed

#84 feat: performs readiness check on couchdb instance
  .gitignore
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/couchdb/errors.go
  scripts/check_unit.sh
Labels: cla-signed, enhancement

#87 chore: upgrade golang to 1.15
  .gitignore
  .golangci.yml
  README.md
  ci/azure-pipelines.yml
  pkg/internal/logging/metadata/callerInfo.go
  pkg/internal/logging/metadata/callerInfo_test.go
  pkg/internal/logging/metadata/level.go
  pkg/internal/logging/metadata/level_test.go
  pkg/internal/logging/metadata/opts.go
  pkg/internal/logging/metadata/opts_test.go
  pkg/internal/logging/metadata/util_test.go
  pkg/internal/logging/metadata/utils.go
  pkg/internal/logging/modlog/deflog.go
  pkg/internal/logging/modlog/deflog_test.go
  pkg/internal/logging/modlog/logapi.go
  pkg/internal/logging/modlog/logtestutils.go
  pkg/internal/logging/modlog/modlog.go
  pkg/internal/logging/modlog/modlog_test.go
  pkg/internal/support/httphandler.go
  pkg/internal/support/httphandler_test.go
  pkg/log/api.go
  pkg/log/logger.go
  pkg/log/logger_test.go
  pkg/log/provider.go
  pkg/log/provider_test.go
  pkg/restapi/internal/common/http/common.go
  pkg/restapi/logspec/controller_test.go
  pkg/restapi/logspec/operation/openapi.go
  pkg/restapi/logspec/operation/operations.go
  pkg/restapi/logspec/operation/operations_test.go
  pkg/sss/base/splitter_test.go
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/couchdb/errors.go
  pkg/storage/memstore/memstore.go
  pkg/storage/memstore/memstore_test.go
  pkg/storage/mockstore/mockstore.go
  pkg/storage/mysql/errors.go
  pkg/storage/mysql/mysqlstore.go
  pkg/storage/mysql/mysqlstore_test.go
  pkg/tls/certpool.go
  pkg/tls/certpool_test.go
  pkg/utils/cmd/util.go
  pkg/utils/cmd/util_test.go
  pkg/utils/retry/example_test.go
  pkg/utils/retry/retry_test.go
  pkg/utils/tls/util.go
  pkg/utils/tls/util_test.go
  scripts/check_lint.sh
Labels: chore, cla-signed

#85 fix: couchDB checks for existence of '_users' db in ping
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
  pkg/storage/couchdb/errors.go
  scripts/check_unit.sh
  scripts/couchdb-config/config.ini
Labels: cla-signed

#88 feat: #79 parse HTTP sig header
  pkg/httpsig/canonicalize.go
  pkg/httpsig/parse.go
  pkg/httpsig/parse_test.go
  pkg/httpsig/verify.go
  pkg/httpsig/verify_test.go
Labels: cla-signed, enhancement

#90 fix: couchdb store ignore 'deleted' error
  pkg/storage/couchdb/couchdbstore.go
  pkg/storage/couchdb/couchdbstore_test.go
Labels: cla-signed

#93 feat: #92 parse zcaps
  go.mod
  go.sum
  pkg/httpsig/canonicalize.go
  pkg/httpsig/parse.go
  pkg/httpsig/parse_test.go
  pkg/httpsig/verify.go
  pkg/httpsig/verify_test.go
  pkg/zcapld/resolve.go
  pkg/zcapld/verify.go
  pkg/zcapld/verify_test.go
  pkg/zcapld/zcap.go
Labels: cla-signed, enhancement
